# Generated by Django 3.0.10 on 2021-06-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='city',
        ),
        migrations.RemoveField(
            model_name='app',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='app',
            name='state',
        ),
    ]
